import Home from './home/Home'
import NewProduct from './newProduct/newProduct'
import NewUser from './newUser/NewUser'
import Product from './product/Product'
import ProductList from './productList/ProductList'
import User from './userPage/User'
import UserList from './userList/userList'
export { Home }
export { NewProduct }
export { NewUser }
export { Product }
export { ProductList }
export { UserList }
export { User }
