import newProduct from './newProduct/NewProduct'
export { newProduct }
import newUser from './newUser/NewUser'
export { newUser }
import Product from './product/Product'
export { Product }
import ProductList from './productList/ProductList'
export { ProductList }
import UserList from './userList/UserList'
export { UserList }
import User from './user/User'
export { User }
